### ISSUE TITLE
Issues with joysticks on the last release 

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/PCXT_MiSTer#13]
Hi @Flandango 

For the both joysticks, It will be great to add 'none' in the values like AO486.
Because, the game Paratrooper is kind of weird. It passes the screen "select between keyboard and joystick" without any action on my side. Maybe this game doesn't like both joysticks connected at the same time.

Thanks !

**Comment by Flandango** [comment]
Paratrooper does have a known issue were it auto starts when there's a second joystick plugged in.
I'll look into adding the option(s) to disable the controllers.

**Comment by wwark** [comment]
I have compiled the PRERELEASE branch and now the screen to choose Keyboard or Joystick is proposed if the second joystick is disabled. Thank you :+1: 

I have another point for this game.
If we select joystick mode, the canon is stuck at some point on the right side, the left side is ok. If we play with the keyboard the behavior is good.

Keyboard mode:
![20220827_095044-screen](https://user-images.githubusercontent.com/469461/187020796-54e0e8ce-ae4f-4141-88cd-46a7bec467c9.png)

Joystick mode:
![20220827_095146-screen](https://user-images.githubusercontent.com/469461/187020803-4c9c7c58-ffab-4f85-9b98-450041d36368.png)

Thanks again for your time.

**Comment by Flandango** [comment]
What CPU speed are you running this at?  If not 4.77, then try setting the Sync Joy to CPU Speed to YES and see if you get better results.

**Comment by wwark** [comment]
The cpu speed is set 4.77Mhz in this case.
WIth the same speed cpu I set also Sync Joy to CPU to yes but the issue remains.

Do I need to change speed cpu to make more tests ?

**Comment by Flandango** [comment]
If cpu is set at 4.77 then the Sync option being on or off behaves the same so you should be fine there.
I am going to do a fresh pull of the PRERELEASE and test it out in the event I failed to push something up.
In the mean time....
Does the canon move at all when you move the joystick?
Are you using an analog controller?  If so, are they configured in Main?
Can you try switching the joystick option to Digital and try using a DPAD to see if the behavior is the same?

**Comment by wwark** [comment]
I use a M30 8bitdo controller configured analogue and DPAD at the same time.
I tried Digital and Analogue setting on OSD and I have the same result.
The canon moves with my controller.

If I moved the canon up to the limit on the left side, i have the same position of the canon with the joystick and keyboard like the screenshot below
Joystick mode:
![20220827_154648-screen](https://user-images.githubusercontent.com/469461/187033165-34aac227-1f18-4203-8d0b-7aeb669951f7.png)

Keyboard mode:
![20220827_154738-screen](https://user-images.githubusercontent.com/469461/187033177-06074c73-43a0-4a9a-8996-1a6276042469.png)

But if I moved the canon up to the limit on the right side, i don't have the same position of the canon with the joystick and keyboard like the screenshot on my previous comment.
The canon stops before with joystick and can't go to the same position like the keyboard

**Comment by Flandango** [comment]
Ah ok.  Yes I get the same result.  I misunderstood and thought the cannon was stuck in that position.
I found the same result with Mame and PCEM.
What I found to work best with that game is to set the CPU at 7.16 and turn the Sync option off.
Then you get full range of motion.  Similar how pacman works.  Pacman needs 7.16 and no adjustment to gameport speed (i.e. Sync is off)

**Comment by wwark** [comment]
Thanks for the information. It works perfectly now with your advice !
I will put this game on 716Mhz directory !
I close this ticket.
