### ISSUE TITLE
MDA resolution screwed up

### ISSUE THREAD

**Issue by somhi** [MiSTer-devel/PCXT_MiSTer#16]
Latests scanlines additions screwed up the MDA video output. 
Does not seem important to solve this right now, but is better to have it annotated here as an issue.
@Newsdee was working on it, I think.

**Comment by spark2k06** [comment]
Your pull request solves the problem, thank you!

https://github.com/MiSTer-devel/PCXT_MiSTer/pull/17

I close the issue.
