### ISSUE TITLE
Landmark System Speed Test 6.00 crashes the core.

### ISSUE THREAD

**Issue by Hodor-git** [MiSTer-devel/PCXT_MiSTer#26]
Landmark System Speed Test 6.00 crashes the core once completed choosing either XT or Tandy configuration. On the contrary it works fine on 86Box emulator. Unfortunately, I can´t test it on real hardware.

[LM60.zip](https://github.com/MiSTer-devel/PCXT_MiSTer/files/9526132/LM60.zip)

**Comment by spark2k06** [comment]
The bug be related to the use of floating point. I am isolating the problem to find a solution, which is probably at the MCL86 microcode level.

**Comment by spark2k06** [comment]
Fixed:

https://misterfpga.org/viewtopic.php?t=5610
