### ISSUE TITLE
Keyb sp  or any other language is giving a lot of troubles with keyboard

### ISSUE THREAD

**Issue by somhi** [MiSTer-devel/PCXT_MiSTer#27]
After loading keyb sp or any other language, after pressing Shift key, you cannot go back to write in lower-case letters. Also in edit for example the ESC key does not work.

I've tested a program called keybsp v5.0 from CiriSOFT and is working well.

**Comment by jsmolina** [comment]
I've been investigating and trying with both dosbox and the core.

Scancode is correct, but I got an absolute hang here:
![WhatsApp Image 2022-10-28 at 20 59 56](https://user-images.githubusercontent.com/447481/198712617-16c50d4c-e940-4c3d-a7d6-5ec6e44dc546.jpeg)


This is dosbox behaviour:
https://user-images.githubusercontent.com/447481/198712764-e96d751a-d760-4af8-aa96-6f965d520728.mov

**Comment by jsmolina** [comment]
[KEY2.zip](https://github.com/MiSTer-devel/PCXT_MiSTer/files/9891106/KEY2.zip)
This is the code I used

**Comment by spark2k06** [comment]
This application also hangs on 86Box/PCem with the IBM PC machine (1982), for example..., it is not useful for testing.

**Comment by spark2k06** [comment]
Investigating further together with kitune-san, we have located the bug, which is in the MCL86 core:

MCL86:

![image](https://user-images.githubusercontent.com/3509674/198845806-58c02bb5-ae8c-4417-b86f-350a590523c0.png)

PCem/86Box:

![image](https://user-images.githubusercontent.com/3509674/198845816-a9cb3642-d43b-44e7-96f8-4e099202ff99.png)

@kitune-san poses the following solution in the MCL86 microcode:

https://github.com/MiSTer-devel/PCXT_MiSTer/commit/ad211c33e262d7fb637e9462945fc47f311765b2

@MicroCoreLabs is making sure it's all correct and this doesn't affect  other 0xF6 opcodes.

**Comment by spark2k06** [comment]
@MicroCoreLabs confirms that everything is correct. Thank you all.
