### ISSUE TITLE
Tandy sound volume is too low

### ISSUE THREAD

**Issue by mills32** [MiSTer-devel/PCXT_MiSTer#29]
Volume is too low for the tandy sound chip, in all tests I made. There are for example, some games (castlevania) which use tandy sound + pc speaker, and tandy is barery audible.

**Comment by spark2k06** [comment]
The audio system has been substantially improved as it is based on the same ao486, allowing volume control of PCSpeaker and Tandy Sound, as well as the addition of Audio Boost and Stereo Mix:

https://misterfpga.org/viewtopic.php?t=5385
