### ISSUE TITLE
Bubble Bobble intro music sounds like a warped record

### ISSUE THREAD

**Issue by famiclone6502** [MiSTer-devel/PCXT_MiSTer#47]
I have a real Tandy 1000 SX and the music has a normal steady pace, but on the MiSTer core it either goes too fast or too slow in a strange rhythm, like a warped record. Make sure you don't use any UMB settings as the game is incompatible with it even on real hardware.* It seems to need to be run at the lowest clock speed, too. Although on real hardware the gameplay runs more smoothly switching from 8088 to 286 mode (using a 286Xpress card), so I don't know if the higher clock speed should be causing issues, either.  

*Note: Enabling UMB (like the standard boot HD image includes) will cause it to crash specifically with TGA graphics/sound, but using F8 as DOS starts to bypass those settings will let you experience the issue without crashes. This crash is not a core issue as it happens on real hardware, and also does not seem to occur with other graphics modes like CGA. So you may have to delete the .cfg file to change the game's settings for Tandy.

**Comment by spark2k06** [comment]
Fixed by @kitune-san, now in pre-release, soon available in the release version.

https://github.com/MiSTer-devel/PCXT_MiSTer/pull/67
