### ISSUE TITLE
Black lines between rows with Tandy DOS text mode (example: MS DOS Edit)

### ISSUE THREAD

**Issue by famiclone6502** [MiSTer-devel/PCXT_MiSTer#54]
Per the info you provided in our conversation, a real Tandy uses 225 lines for text mode and does not show black lines between each row. In my opinion, replicating the last row would be the best option for the sake of accuracy.

**Comment by mills32** [comment]
I could test a real tandy 1000 computer, it adds black lines in all characters except for these: 
8,10, 208 to 223.
Tandy does not duplicate the last line, it writes the fist character line again, and only for line 8 (9), if you configure character cells to be 10 pixels tall, tandy just adds black or background pixels.

Other graphic cards, like EGA/VGA, also repeat these "box" characters beyond line 14 (EGA) and 16 (VGA)

**Comment by spark2k06** [comment]
Thank you both! This issue will be resolved in the next release:

![image](https://user-images.githubusercontent.com/3509674/202224571-0d6f98f7-60fe-4ac5-9a4f-55e5bfe09c9b.png)
