### ISSUE TITLE
Simpsons arcade game: won't detect TANDY

### ISSUE THREAD

**Issue by jsmolina** [MiSTer-devel/PCXT_MiSTer#55]
It shows something very close to this:
![image](https://user-images.githubusercontent.com/447481/199531515-417747a9-143c-4086-b23d-1c05dc832edf.png)

With EGA and tandy disabled, even on tandy mode.

86box shows the option enabled (using same PCXT_CGA_Tandy_2.3.img
![image](https://user-images.githubusercontent.com/447481/199532546-724736c8-607c-4d61-bde5-1ed4efdf753d.png)

**Comment by spark2k06** [comment]
Fixed in release 20221106

![20221105_070244-screen](https://user-images.githubusercontent.com/3509674/200183407-0fbab95d-440a-4bf9-8354-5fffe69fb3bb.png)
