### ISSUE TITLE
PCXT core cpu speed 10Mhz possible?

### ISSUE THREAD

**Issue by suww37** [MiSTer-devel/PCXT_MiSTer#56]
Currently, the cpu speed of the pcxt core can be adjusted in three steps: 4.77Mhz, 7Mhz, and 14Mhz. By the way, the xt pc I used a long time ago had a cpu speed of 10Mhz. I want to recreate this CPU speed, but I wonder if this is possible in the pcxt core now.

**Comment by spark2k06** [comment]
Already implemented, currently in prerelease mode:

https://misterfpga.org/viewtopic.php?t=5611#p63649

Soon to be released for everyone, I close issue.
