### ISSUE TITLE
Tandy Mode - Civilization 1 - hangs during "building new world"

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/PCXT_MiSTer#59]
Hi,
After starting the new game of Civilization 1 with Tandy Mode, the game hangs at the step "BUILDING NEW WORLD"
If we load a save, it goes in game.

![20221106_183339-screen](https://user-images.githubusercontent.com/469461/200185997-4ee35ab1-5f24-422a-bbee-f3ee7dec92db.png)
Thanks,

**Comment by spark2k06** [comment]
Maybe you didn't wait long enough, but it did load me:

![20221106_194447-screen](https://user-images.githubusercontent.com/3509674/200189297-69ca9b98-3c74-49e9-8350-0f9f89023b1c.png)

Note that right now the core is running on serdrive, which is much slower than a real IDE.

**Comment by wwark** [comment]
You are right I think waiting a lot so I think the core hangs.
But it goes in game just need to wait a little more.
Thank you for the check will close this ticket.
