### ISSUE TITLE
PKUNZIP failing CRC checks in PCXT (works in AO486)

### ISSUE THREAD

**Issue by flynnsbit** [MiSTer-devel/PCXT_MiSTer#6]
Issue:  most zip extraction throws CRC failures on some files if you use pkunzip to either test (-t) or extract them onto the disk.  I tested both Tandy and IBM bios files, different disk sizes, COM speeds at 115 and 460.

To duplicate: on PC-DOS 2000 or MS-DOS 6.22 run "PKUNZIP -t zipfile.zip" or "PKUNZIP -+ -- -d FILE.ZIP C:\DIRECTORY" and you will see the CRC errors warnings "file fails CRC checks"

PKUNZIP version 2.04g used and can be pulled from the C:\TDL\UTILS directory in the zip referenced below.  

Easiest test would be to grab the tdl_small.zip file on anonymous@ftp.oldskool.org/pub/TDL_TEST/tdl_small.zip and extract.  A good zip to test with is C:\TDL\Files\FAHRENHE.ZIP.  There are multiple files in that zip that will fail.  Chessmaster and ALTEREDD.ZIP will also fail.  Maybe it is the size of the zip files.

Some of the zip files are fine on the PCXT core and I can't figure out the difference. 

Hoping someone can figure this one out.  Also, attaching the exact same disk (renamed to vhd) on AO486 and running PKUNZIP works correctly for all files.

**Comment by spark2k06** [comment]
All these problems are due to the use of serdrive for disk management, maybe @kitune-san can think of a way to fix it, with more delay on the uart module maybe? 

In any case, we may have to assume these drawbacks until we have IDE and floppy and can do without serdrive, the time spent on improving the latter should be minimal, because in the end we will discard it.

**Comment by spark2k06** [comment]
Although the use of CTS/RTS would improve transfer reliability, especially at very high speeds like 921.6Kbps... I am convinced that this is not the problem with file extraction using PKZIP 2.0+.

I have noticed that the CRC failures always occur on the same files, and by doing several extractions at different speeds, the extracted content always matches, i.e. it extracts the same bad bytes every time.

With this I come to the conclusion that there must be some incompatibility with the XTIDE BIOS when using the serial port, I wish I could have tested it on a real PCXT through its RS232 port connected to the PC, but as always happens, right now I lack a NULL-MODEM RS232 cable to test the connection with another PC using serdrive, a connection that probably also makes use of the CTS/RTS signals.

Maybe someone can do this test to confirm my theory, if not, I'll get some cable and try it when I can.

**Comment by spark2k06** [comment]
If the extraction is carried out on a RAM unit there are also CRC failures, it seems to be a failure of the IP CORE MCL86 or of the PCXT core itself and not of serdrive... further investigation will be necessary.

**Comment by spark2k06** [comment]
Besides PKZIP2.0+, there may be more applications and games that don't work for similar reasons, the main suspect is MCL86 but we'll have to see.

The best way to know if the reason for not loading an 8088 compatible app is the serdrive, from now on would be to make use of RAMDISK, and if it doesn't work here, the problem with serdrive would be ruled out.

For example, I've already found some other game that didn't work, like TAPPER, although not the original pcbooter, that works fine, but a modified and executable one from MSDos... it returns a "Disk Error" message... it could be for the same reason as PKZIP 2.0+ but unlike this one I think it will be easier to debug it, and that will be the next thing I'll do.

**Comment by spark2k06** [comment]
Issue resolved between @kitune-san y @MicroCoreLabs

https://github.com/MiSTer-devel/PCXT_MiSTer/pull/18
