### ISSUE TITLE
COM2 Support

### ISSUE THREAD

**Issue by bbond007** [MiSTer-devel/PCXT_MiSTer#62]
Do you think you could make COM2 connected to /dev/ttyS1 so that it would work with the TCP modem? There are quite a few Telnet BBS's out there --> https://www.telnetbbsguide.com/

This would also allow you to download files from the Linux filesystem to the PCXT .IMG file via Zmodem.  For example if you needed a small file such as a device driver..

Thanks for this great core!

**Comment by spark2k06** [comment]
UART OSD option added, close this issue.
