### ISSUE TITLE
ROM script doesn't work on case-sensitive systems

### ISSUE THREAD

**Issue by arromdee** [MiSTer-devel/PCXT_MiSTer#7]
On Linux, make_rom_with_ibm5160.py produces an error:

Traceback (most recent call last):
  File "make_rom_with_ibm5160.py", line 28, in <module>
    with open(rom_filename, "wb") as romf, open(ibm5160_basename + "U19_5000027_27256.bin", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'BIOS_5160_08NOV82_U19_5000027_27256.bin'

because the filenames end in uppercase "BIN".  

The other two seem to be okay.

**Comment by spark2k06** [comment]
Resolved for the next release:

https://github.com/MiSTer-devel/PCXT_MiSTer/commit/92e4ab8937e23352b3d4ab6ceaa6e256a4fcaf28
